name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate JSON workflows
        run: |
          sudo apt-get update && sudo apt-get install -y jq
          jq . workflows/*.json >/dev/null
